import "@/app/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function LoginLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section>{children}</section>
      </body>
    </html>
  );
}
