import "@/app/globals.css";
import "react-toastify/dist/ReactToastify.css";

import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { ToastContainer } from "@/components/Toast/ToastWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function LoginLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <section>{children}</section>
      </body>
    </html>
  );
}
