import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

import NextTopLoader from "nextjs-toploader";

import { Inter } from "next/font/google";

import AuthProvider from "@/components/Auth/AuthProvider";
import ProductProvider from "@/context/ProductContext";
import CartProvider from "@/context/CartContext";
import Navbar from "@/components/Header/Navbar";
import Cart from "@/components/Cart/Cart";
import CartItemProvider from "@/context/CartItemContext";
import { ToastContainer } from "@/components/Toast/ToastWrapper";
import SearchProvoder from "@/context/SearchContext";
import CheckoutProvider from "@/context/ChechoutContext";
import Favicon from "/public/logo.png";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Book Store",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: Favicon.src }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader
          color="#2299DD"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          easing="ease"
          showSpinner={false}
          speed={200}
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
        />
        <ToastContainer />
        <CheckoutProvider>
          <SearchProvoder>
            <CartProvider>
              <CartItemProvider>
                <ProductProvider>
                  <AuthProvider>
                    <Navbar />
                    <Cart />
                    {children}
                  </AuthProvider>
                </ProductProvider>
              </CartItemProvider>
            </CartProvider>
          </SearchProvoder>
        </CheckoutProvider>
      </body>
    </html>
  );
}
