import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

import { Inter } from "next/font/google";

import AuthProvider from "@/components/Auth/AuthProvider";
import ProductProvider from "@/context/ProductContext";
import CartProvider from "@/context/CartContext";
import Navbar from "@/components/Header/Navbar";
import Cart from "@/components/Cart/Cart";
import CartItemProvider from "@/context/CartItemContext";
import { ToastContainer } from "@/components/Toast/ToastWrapper";
import SearchProvoder from "@/context/SearchContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Book Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <SearchProvoder>
          <CartProvider>
            <CartItemProvider>
              <ProductProvider>
                <AuthProvider>
                  <Navbar />
                  <Cart />
                  {children}
                </AuthProvider>
              </ProductProvider>
            </CartItemProvider>
          </CartProvider>
        </SearchProvoder>
      </body>
    </html>
  );
}
